// Generated by Supabase CLI. Committed for CI/builds.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "13.0.5"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      chat_messages: {
        Row: {
          ai_response: string
          context_movies: Json | null
          created_at: string | null
          id: string
          user_id: string
          user_message: string
        }
        Insert: {
          ai_response: string
          context_movies?: Json | null
          created_at?: string | null
          id?: string
          user_id: string
          user_message: string
        }
        Update: {
          ai_response?: string
          context_movies?: Json | null
          created_at?: string | null
          id?: string
          user_id?: string
          user_message?: string
        }
        Relationships: []
      }
      import_progress: {
        Row: {
          category: string
          content_type: string
          created_at: string | null
          id: string
          last_page: number
          last_run: string | null
          notes: string | null
          total_imported: number | null
          total_skipped: number | null
          updated_at: string | null
          year: number | null
        }
        Insert: {
          category: string
          content_type: string
          created_at?: string | null
          id?: string
          last_page?: number
          last_run?: string | null
          notes?: string | null
          total_imported?: number | null
          total_skipped?: number | null
          updated_at?: string | null
          year?: number | null
        }
        Update: {
          category?: string
          content_type?: string
          created_at?: string | null
          id?: string
          last_page?: number
          last_run?: string | null
          notes?: string | null
          total_imported?: number | null
          total_skipped?: number | null
          updated_at?: string | null
          year?: number | null
        }
        Relationships: []
      }
      movies: {
        Row: {
          backdrop_url: string | null
          created_at: string | null
          crew: Json | null
          description: string | null
          embedding: string | null
          genres: string[] | null
          id: number
          keywords: string[] | null
          movie_cast: Json | null
          original_language: string | null
          popularity: number | null
          poster_url: string | null
          production_companies: string[] | null
          release_date: string | null
          runtime: number | null
          tagline: string | null
          title: string
          translations: Json | null
          updated_at: string | null
          vote_average: number | null
          vote_count: number | null
        }
        Insert: {
          backdrop_url?: string | null
          created_at?: string | null
          crew?: Json | null
          description?: string | null
          embedding?: string | null
          genres?: string[] | null
          id: number
          keywords?: string[] | null
          movie_cast?: Json | null
          original_language?: string | null
          popularity?: number | null
          poster_url?: string | null
          production_companies?: string[] | null
          release_date?: string | null
          runtime?: number | null
          tagline?: string | null
          title: string
          translations?: Json | null
          updated_at?: string | null
          vote_average?: number | null
          vote_count?: number | null
        }
        Update: {
          backdrop_url?: string | null
          created_at?: string | null
          crew?: Json | null
          description?: string | null
          embedding?: string | null
          genres?: string[] | null
          id?: number
          keywords?: string[] | null
          movie_cast?: Json | null
          original_language?: string | null
          popularity?: number | null
          poster_url?: string | null
          production_companies?: string[] | null
          release_date?: string | null
          runtime?: number | null
          tagline?: string | null
          title?: string
          translations?: Json | null
          updated_at?: string | null
          vote_average?: number | null
          vote_count?: number | null
        }
        Relationships: []
      }
      tv_episodes: {
        Row: {
          air_date: string | null
          created_at: string | null
          episode_number: number
          id: number
          name: string | null
          overview: string | null
          runtime: number | null
          season_id: number | null
          still_url: string | null
          tv_show_id: number | null
          vote_average: number | null
          vote_count: number | null
        }
        Insert: {
          air_date?: string | null
          created_at?: string | null
          episode_number: number
          id: number
          name?: string | null
          overview?: string | null
          runtime?: number | null
          season_id?: number | null
          still_url?: string | null
          tv_show_id?: number | null
          vote_average?: number | null
          vote_count?: number | null
        }
        Update: {
          air_date?: string | null
          created_at?: string | null
          episode_number?: number
          id?: number
          name?: string | null
          overview?: string | null
          runtime?: number | null
          season_id?: number | null
          still_url?: string | null
          tv_show_id?: number | null
          vote_average?: number | null
          vote_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "tv_episodes_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "tv_seasons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tv_episodes_tv_show_id_fkey"
            columns: ["tv_show_id"]
            isOneToOne: false
            referencedRelation: "tv_shows"
            referencedColumns: ["id"]
          },
        ]
      }
      tv_seasons: {
        Row: {
          air_date: string | null
          created_at: string | null
          episode_count: number | null
          id: number
          name: string | null
          overview: string | null
          poster_url: string | null
          season_number: number
          tv_show_id: number | null
          vote_average: number | null
        }
        Insert: {
          air_date?: string | null
          created_at?: string | null
          episode_count?: number | null
          id: number
          name?: string | null
          overview?: string | null
          poster_url?: string | null
          season_number: number
          tv_show_id?: number | null
          vote_average?: number | null
        }
        Update: {
          air_date?: string | null
          created_at?: string | null
          episode_count?: number | null
          id?: number
          name?: string | null
          overview?: string | null
          poster_url?: string | null
          season_number?: number
          tv_show_id?: number | null
          vote_average?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "tv_seasons_tv_show_id_fkey"
            columns: ["tv_show_id"]
            isOneToOne: false
            referencedRelation: "tv_shows"
            referencedColumns: ["id"]
          },
        ]
      }
      tv_shows: {
        Row: {
          backdrop_url: string | null
          created_at: string | null
          crew: Json | null
          embedding: string | null
          first_air_date: string | null
          genres: string[] | null
          id: number
          keywords: string[] | null
          last_air_date: string | null
          name: string
          number_of_episodes: number | null
          number_of_seasons: number | null
          origin_country: string[] | null
          original_language: string | null
          overview: string | null
          popularity: number | null
          poster_url: string | null
          production_companies: string[] | null
          status: string | null
          tagline: string | null
          translations: Json | null
          tv_cast: Json | null
          updated_at: string | null
          vote_average: number | null
          vote_count: number | null
        }
        Insert: {
          backdrop_url?: string | null
          created_at?: string | null
          crew?: Json | null
          embedding?: string | null
          first_air_date?: string | null
          genres?: string[] | null
          id: number
          keywords?: string[] | null
          last_air_date?: string | null
          name: string
          number_of_episodes?: number | null
          number_of_seasons?: number | null
          origin_country?: string[] | null
          original_language?: string | null
          overview?: string | null
          popularity?: number | null
          poster_url?: string | null
          production_companies?: string[] | null
          status?: string | null
          tagline?: string | null
          translations?: Json | null
          tv_cast?: Json | null
          updated_at?: string | null
          vote_average?: number | null
          vote_count?: number | null
        }
        Update: {
          backdrop_url?: string | null
          created_at?: string | null
          crew?: Json | null
          embedding?: string | null
          first_air_date?: string | null
          genres?: string[] | null
          id?: number
          keywords?: string[] | null
          last_air_date?: string | null
          name?: string
          number_of_episodes?: number | null
          number_of_seasons?: number | null
          origin_country?: string[] | null
          original_language?: string | null
          overview?: string | null
          popularity?: number | null
          poster_url?: string | null
          production_companies?: string[] | null
          status?: string | null
          tagline?: string | null
          translations?: Json | null
          tv_cast?: Json | null
          updated_at?: string | null
          vote_average?: number | null
          vote_count?: number | null
        }
        Relationships: []
      }
      user_profiles: {
        Row: {
          prefs_embedding: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          prefs_embedding?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          prefs_embedding?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_profiles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      user_tv_watchlist: {
        Row: {
          created_at: string | null
          progress_episode: number | null
          progress_season: number | null
          rating: number | null
          status: string
          tv_show_id: number
          updated_at: string | null
          user_id: string
          watched_at: string | null
        }
        Insert: {
          created_at?: string | null
          progress_episode?: number | null
          progress_season?: number | null
          rating?: number | null
          status: string
          tv_show_id: number
          updated_at?: string | null
          user_id: string
          watched_at?: string | null
        }
        Update: {
          created_at?: string | null
          progress_episode?: number | null
          progress_season?: number | null
          rating?: number | null
          status?: string
          tv_show_id?: number
          updated_at?: string | null
          user_id?: string
          watched_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "user_tv_watchlist_tv_show_id_fkey"
            columns: ["tv_show_id"]
            isOneToOne: false
            referencedRelation: "tv_shows"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_tv_watchlist_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      user_watchlist: {
        Row: {
          created_at: string | null
          movie_id: number
          rating: number | null
          status: string
          updated_at: string | null
          user_id: string
          watched_at: string | null
        }
        Insert: {
          created_at?: string | null
          movie_id: number
          rating?: number | null
          status: string
          updated_at?: string | null
          user_id: string
          watched_at?: string | null
        }
        Update: {
          created_at?: string | null
          movie_id?: number
          rating?: number | null
          status?: string
          updated_at?: string | null
          user_id?: string
          watched_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "user_watchlist_movie_id_fkey"
            columns: ["movie_id"]
            isOneToOne: false
            referencedRelation: "movies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_watchlist_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          created_at: string | null
          email: string
          id: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          email: string
          id?: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          email?: string
          id?: string
          updated_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_next_import_page: {
        Args: { p_category: string; p_content_type: string; p_year?: number }
        Returns: number
      }
      get_similar_movies: {
        Args: { match_count?: number; p_movie_id: number }
        Returns: {
          backdrop_url: string
          description: string
          genres: string[]
          id: number
          popularity: number
          poster_url: string
          release_date: string
          similarity: number
          title: string
          vote_average: number
        }[]
      }
      get_translated_field: {
        Args: {
          fallback_value?: string
          field_name: string
          language?: string
          translations_json: Json
        }
        Returns: string
      }
      match_movies: {
        Args: {
          filter_ids?: number[]
          match_count?: number
          query_embedding: string
        }
        Returns: {
          backdrop_url: string
          description: string
          genres: string[]
          id: number
          popularity: number
          poster_url: string
          release_date: string
          similarity: number
          title: string
          vote_average: number
        }[]
      }
      match_movies_by_profile: {
        Args: { match_count?: number; p_user_id: string }
        Returns: {
          backdrop_url: string
          description: string
          genres: string[]
          id: number
          popularity: number
          poster_url: string
          release_date: string
          similarity: number
          title: string
          vote_average: number
        }[]
      }
      match_tv_shows: {
        Args: {
          filter_ids?: number[]
          match_count?: number
          query_embedding: string
        }
        Returns: {
          backdrop_url: string
          id: number
          name: string
          overview: string
          popularity: number
          poster_url: string
          similarity: number
          vote_average: number
        }[]
      }
      update_import_progress: {
        Args: {
          p_category: string
          p_content_type: string
          p_imported?: number
          p_last_page: number
          p_skipped?: number
          p_year: number
        }
        Returns: undefined
      }
      update_user_profile_embedding: {
        Args: { min_rating?: number; p_user_id: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const
